baseURL: 'https://precisiondocs.netlify.app/'
languageCode: en-us
title: Fabrizio Ulisse / Precision Docs
theme: PaperMod
params:
  env: production
  DateFormat: 'January 2, 2006'
  defaultTheme: auto
  disableThemeToggle: true
  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: false
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: false
  ShowWordCount: false
  ShowRssButtonInSectionTermList: false
  UseHugoToc: true
  disableSpecial1stPost: true
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: false
  tocopen: false
  assets:
    favicon: <link / abs url>
    favicon16x16: <link / abs url>
    favicon32x32: <link / abs url>
    apple_touch_icon: <link / abs url>
    safari_pinned_tab: <link / abs url>
  label:
    text: Fabrizio Ulisse / Precision Docs
    icon: /apple-touch-icon.png
    iconHeight: 35
  profileMode:
    enabled: false
    title: Fabrizio Ulisse / Precision Docs
    subtitle: This is subtitle
    imageUrl: <img location>
    imageWidth: 120
    imageHeight: 120
    imageTitle: my image
    buttons:
      - name: Posts
        url: posts
      - name: Tags
        url: tags
  homeInfoParams:
    Title: "Hi there \U0001F44B"
    Content: Welcome to my blog
  socialIcons:
    - name: x
      url: 'https://x.com/'
    - name: stackoverflow
      url: 'https://stackoverflow.com'
    - name: github
      url: 'https://github.com/biccio'
  analytics:
    google:
      SiteVerificationTag: XYZabc
    bing:
      SiteVerificationTag: XYZabc
    yandex:
      SiteVerificationTag: XYZabc
  cover:
    hidden: true
    hiddenInList: true
    hiddenInSingle: true
  editPost:
    URL: 'https://github.com/<path_to_repo>/content'
    Text: Suggest Changes
    appendFilePath: true
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    limit: 10
    keys:
      - title
      - permalink
      - summary
      - content
menu:
  main:
    - identifier: categories
      name: categories
      url: /categories/
      weight: 10
    - identifier: tags
      name: tags
      url: /tags/
      weight: 20
    - identifier: example
      name: example.org
      url: 'https://example.org'
      weight: 30
markup:
  highlight:
    noClasses: false
