baseURL = "https://precisiondocs.tech/"
languageCode = "en-us"
theme = "anubis2"
title = "PrecisionDocs"

[author]
name = "Fabrizio Ulisse"

[markup.goldmark.renderer]
unsafe = true # Enable unsafe mode to have a better experience

[markup.highlight]
anchorLineNos      = false
codeFences         = true
style              = '1c-light'
tabWidth           = 4


[pagination]
pagerSize = 5

[params]
description = "Tech and docs writing resources and stuff"
dateFormat = "2006-01-02"
paginationSinglePost = true
colorTheme = "auto"
colorThemeSwitcher = false
rssAsSocialIcon = true
anchorLineNos      = false

customCSS = ["custom-css/custom-css1.css"]


social = [
    { id = "github", url = "https://github.com/biccio" },
    { id = "linkedin", url = "https://www.linkedin.com/in/fabrizioulisse" },
]

[[menu.main]]
identifier = "home"
name = "Home"
url = "/"
weight = 1

[[menu.main]]
identifier = "about"
name = "About"
url = "/about/"
weight = 2

[[menu.main]]
identifier = "tags"
name = "Tags"
url = "/tags/"
weight = 3

[params.GoogleAnalytics]
enabled = true
gtag = "G-8TN2DVWLG0"
