baseURL = 'https://precisiondocs.netlify.app/'
languageCode = 'en-us'
title = 'Precision Docs'
theme = 'paper'
[params]
  # color style
  color = 'grey'
github = 'biccio'
linkedin = 'fabrizioulisse'
mastodon = 'https://hachyderm.io/@biccio'
rss = true

# home page profile
avatar = 'https://gravatar.com/avatar/fe75b3adddd577cc1ad6d1b9bc250ef1c243f3a23590f7793cb3e97650f9652c'
name = 'Fabrizio Ulisse'
bio = 'Senior Tech Communication @PagoPA 路 #gravel bike rider 路 #stratocaster player 路 Father 路 Humanizing tech complexities for a living since cathode ray tube'
