baseURL = "https://lightbi-hugo-theme.netlify.app/"
DefaultContentLanguage = "en"
defaultContentLanguageInSubdir = false
languageCode = "en-us"
title = "PrecisionDocs"
theme = "lightbi-hugo"
metaDataFormat = "yaml"
pygmentsStyle = "trac"
#pygmentsUseClasses = true
#pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
#pygmentsUseClassic = true
#pygmentOptions = "linenos=inline"
#disqusShortname = "XXX"
#googleAnalytics = "XXX"
enableRobotsTXT = true
enableGitInfo = false
Paginate = 6
summaryLength  = "30"

[Params]
selfHosted = true
mainSections = ["post","posts"]
dateFormat = "02 January 2006"
comments = false
readingTime = false
wordCount = false
useHLJS = true
socialShare = false
delayDisqus = true
showRelatedPosts = true
summaryLength  = "9"
lunrSearch = true
gcse = false
lastmod = false
rss = true
pagination = "10"
hideAuthor = true
description="Your can add your website description here."
previewCardImagePlacement = "top"

[Params.Author]
  name = "Fabrizio Ulisse"
  website = "https://fabrizioulisse.it/"
  authorInfo = "Humanizing Tech Complexities since Cathod-Ray Tubes."
  authorPostImage = "/img/fabrizio-ulisse.jpg"

[Author]
  name = "Fabrizio Ulisse"
  website = "https://fabrizioulisse.it"
  #email = "sample@gmail.com"
  #facebook = "username"
  #instagram = "username"
  #youtube = "user/username" # or channel/channelname
  twitter = "biccio"
  linkedin = "fabrizioulisse"
  github = "biccio"
  threads = "biccio"
  #gitlab = "username"
  #reddit = "username"
  #stackoverflow = "users/XXXXXXX/username"
  #snapchat = "username"
  #spotify = "username"
  #paypal = "username"
  #telegram = "username"
  mastodon = "https://hachyderm.io/@biccio"
  #slack = "username"
  #bandcamp = "username"
  #itchio = "username"
  #vk = "username"
  #500px = "username"
  #kaggle = "username"
  #weibo = "username"
  #xing = "username"
  #bitbucket = "username"
  #soundcloud = "username"
  # codepen = "username"

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

[[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 2

[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 3


[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"


