baseURL = 'https://precisiondocs.netlify.app/'
languageCode = 'en-us'
title = 'Precision Docs'
theme = 'paper'
[params]
  # color style
  color = 'grey'
github = 'biccio'
linkedin = 'ulisse'
mastodon = 'https://hachyderm.io/@biccio'